### ISSUE TITLE
Does not work if AddAuthentication has options

### ISSUE THREAD

**Issue by epitka** [jabbera/aspnetcore-testing-role-handler#21]
If there are options passed to AddAuthentication like this, it does not work, as AddAuthentication then happens after  adding tests services in ClainInjectorWebApplicationFactory. Just add this to your project and run tests and you will see them break.

           services
               .AddAuthentication(options =>
                {
                    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })

**Comment by jabbera** [comment]
Thanks for reporting. Sorted this here: https://github.com/jabbera/aspnetcore-testing-role-handler/pull/22

I'll publish a new package in an hour, but you can sort it yourself locally by overriding: https://github.com/jabbera/aspnetcore-testing-role-handler/blob/master/AspNetCore.Testing.Authentication.ClaimInjector/ClaimInjectorWebApplicationFactory.cs#L44 with the new implementation here: https://github.com/jabbera/aspnetcore-testing-role-handler/pull/22/commits/9c1a26f439724325b228edddd1ecb2987a9df3cf#diff-ff13c22dd16a1dda22aeeb177adb32d3R50

**Comment by jabbera** [comment]
New package published
